training: [{k: 4, n: 4, ans_typ: 3, nr: 2}, {k: 4, n: 4, ans_typ: 3, nr: 2}, {k: 6, n: 4, ans_typ: 3, nr: 2}]

experiment: [{k: 4, n: 4, ans_typ: 2, nr: 3}, {k: 4, n: 4, ans_typ: 3, nr: 3},{k: 4, n: 4, ans_typ: 4, nr: 3},
            {k: 4, n: 5, ans_typ: 2, nr: 3}, {k: 4, n: 5, ans_typ: 3, nr: 3},{k: 4, n: 5, ans_typ: 4, nr: 3},
            {k: 4, n: 6, ans_typ: 2, nr: 3}, {k: 4, n: 6, ans_typ: 3, nr: 3},{k: 4, n: 6, ans_typ: 4, nr: 3},
            {k: 6, n: 4, ans_typ: 2, nr: 3}, {k: 6, n: 4, ans_typ: 3, nr: 3},{k: 6, n: 4, ans_typ: 4, nr: 3},
            {k: 6, n: 5, ans_typ: 2, nr: 3}, {k: 6, n: 5, ans_typ: 3, nr: 3},{k: 6, n: 5, ans_typ: 4, nr: 3},
            {k: 6, n: 6, ans_typ: 2, nr: 3}, {k: 6, n: 6, ans_typ: 3, nr: 3},{k: 6, n: 6, ans_typ: 4, nr: 3}]

# Time
trial_time: 24
click_show_time: 0.3
wait_time: 1.5 # break after trial

# visual parameters
fig_size: 35
sign_size: 35
pair_offset: 30
task_offset: [0, 50]
task_pos: [0, 200]
answers_offset: [150, 0]
answers_pos: [0, 0]
n_columns: 2
columns_offset: 150

TEXT_SIZE: 25

# Frame
frame_height: 50
frame_width: 120
frame_line_width: 3
frame_answer_color: green
frame_click_color: blue

# FEEDB
feedback_in_training: True
feedback_time: -1 # for -1 participant have to presses space
pos_feedb: Poprawna odpowiedź
neg_feedb: Niepoprawna odpowiedź. Poprawna odpowiedź jest pokazana powyżej.
no_feedb: Nie udzieliłeś odpowiedzi. Poprawna odpowiedź jest pokazana powyżej.

# clock
SHOW_CLOCK: 4 # show clock n second before trial end
CLOCK_POS: [0, 350]
CLOCK_SIZE: 120

# OTHER
exit_key: f7
min_training_acc: 0.3
train_trials_randomize: False
exp_trials_randomize: True